# Site Specific Configuration
name: 听松阁
title: 听松阁
description: 归来卧松云，微凉送晚风。枕上听松语，槛外看潮生!
url: https://www.hhhnn.com
author: 听松阁
timezone: America/New_York
timezone_short: ET

# Styling
sass:
  sass_dir: _sass
  style: expanded # compressed, compact, expanded or compressed

#seo
keywords: ['quality', 'software testing', 'QA', 'QE', 'SDET']

# Paginate
pagination:
  enabled: true
  collection: 'posts'
  per_page: 10
  indexpage: 'index'
  sort_field: 'date'
  category: 'posts'
  sort_reverse: true

# Category Paginating
autopages:
  enabled: true
  categories:
    title: 'Posts in category :cat'
    permalink: '/category/:cat'
    silent: false

# Exclusions
exclude: [ 'README.md', 'COPYING', 'drafts', 'templates' ]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-github-metadata

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: cjunius
  hackerrank: cjunius
  instagram: cjunius
  # keybase: your_username
  linkedin: cjunius
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: cjunius
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  youtube: christopherjunius

about:
  description: Husband to a remarkable wife. Father to amazing twin daughters. Caretaker to a dog and two cats. Jack of many trades. Quality Engineering expert.
  interests:
  - name: Test Automation
  - name: Chess 
    link: https://www.chess.com/member/cjunius
  - name: Astronomy
  - name: Star Wars Legos
